### ISSUE TITLE
Need a tactic to extract lifted propositions from a hypothesis.

### ISSUE THREAD

**Issue by Atalay-Ileri** [tchajed/coq-sep-logic#1]
A tactic that transforms 
`H: ([P] * pred) m |-  goal`

to

  `H: ([P] * pred) m,
  H0: P,
  H1: pred m |- goal`

would be great.

**Comment by tchajed** [comment]
That does make sense. I'm thinking that `norm_hyp H` should support a predicate applied to a memory; I'll aim for the resulting state to be

```
H: pred m, H0: P |- goal
```

If you really need the original hypothesis as-is you can always duplicate it and normalize the duplicate instead.

**Comment by tchajed** [comment]
I renamed the old `norm_hyp H` to `norm_with` since it doesn't manipulate `H` at all, and added a `norm_hyp H` that works on an applied predicate, normalizes it, and moves all lifted props out to separate hypotheses.

In the process I decided to make predicates an inductive with a coercion so that `p m` still works but desugars to `predApply p m` - this makes matching on predicate applications reliable and explicit. The downside is that building a predicate now requires `mkPred`, and more importantly proving things about predicates by unfolding them requires a bit more work to simplify `predApply`.
